apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "superapp.fullname" . }}
  labels:
{{ include "superapp.labels.standard" . | indent 4 }}
spec:
  backend:
    serviceName: {{ include "superapp.fullname" . }}
    servicePort: 8080