apiVersion: v1
kind: Service
metadata:
  name: {{ include "superapp.fullname" . }}
  labels:
{{ include "superapp.labels.standard" . | indent 4 }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ template "superapp.name" . }}
    release: {{ .Release.Name | quote }}