version: '1.0'

stages:
  - build
  - release
  - deploy

steps:

  build_image:
    stage: build
    type: build
    image_name: cfdemoacc/superapp
    working_directory: ${{main_clone}}/app/

  push_image:
    stage: release
    type: push
    candidate: '${{build_image}}'
    tag: 'branch-${{CF_BRANCH_TAG_NORMALIZED}}'
    registry: dockerhub

  deploy_chart:
    stage: deploy
    image: cablespaghetti/helmfile-docker:0.0.3
    working_directory: ${{main_clone}}/deploy/
    commands:
      - kubectl config use-context "$KUBE_CONTEXT"
      - export RELEASE_NAME="branch-${{CF_BRANCH_TAG_NORMALIZED}}"
      - helmfile apply