releases:
  - name: superapp-{{ env "RELEASE_NAME" | default "local" }}
    namespace: {{ env "RELEASE_NAME" | default "local" }}
    chart: ./charts/superapp
    values:
    - image:
        tag: {{ env "RELEASE_NAME" | default "latest" }}