releases:
  - name: superapp-{{ env "NAMESPACE" | default "local" }}
    namespace: {{ env "NAMESPACE" | default "local" }}
    chart: ./charts/superapp
    values:
    - image:
        tag: {{ env "NAMESPACE" | default "local" }}